services:
  postgres:
    image: postgres
    networks:
      - examplenetwork
    restart: always
    # healthcheck:
    #   test: [ "CMD", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kawanlama-todo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
  nuxt:
    build: 
      context : .
      dockerfile: Dockerfile
    ports:
      - "1955:1955"
    depends_on:
      - postgres
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    networks:
      - examplenetwork
    env_file: ./.env

networks:
  examplenetwork: 

volumes:
  postgresql:
  postgresql_data:
