version: "3"
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    expose:
      - 5432
  nuxt:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=kawanlama-todo
      - NUXT_SESSION_PASSWORD=password-with-at-least-32-charactersNUXT_SESSION_PASSWORD=aksdlasndkk123kasldkjalsdwdiawak
